#-------------------------------------------------------------------------------
# TOBIAS: DETR instead DeformableDETR
#num_queries: 500
num_queries: 100

#hidden_dim: 288
hidden_dim: 256
#-------------------------------------------------------------------------------
multi_frame_attention: true
multi_frame_encoding: true
multi_frame_attention_separate_encoder: true