#-------------------------------------------------------------------------------
# Register this file in train.py as `wildtrack_only`.
#-------------------------------------------------------------------------------

# starting point: `train_mot17_crowdhuman.yaml`
# dataset-type
dataset: mcmot_less_transforms # less preprocessing to prepare training on 3D data
# don't neet b/c dataset not of type mot_crowdhuman
#crowdhuman_train_split: train_val
train_split: train
val_split: test

mot_path_train: data/multicam_WILDTRACK
#only one sequence at a time to make comparable to distribtion metrics?
mot_path_val: data/multicam_WILDTRACK

# pre-trained detector/tracker
resume: models/mot17_crowdhuman_deformable_multi_frame/checkpoint_epoch_40.pth

epochs: 200
lr_drop: 10

#-------------------------------------------------------------------------------
# must be 1 because I abuse the batch_size dimension for storing data from other
# cams
#-------------------------------------------------------------------------------

batch_size: 1

no_vis: false
vis_and_log_interval: 40 # instead 50

track_query_false_positive_prob: 0.0 # from 0.1
track_query_false_negative_prob: 0.0  # from 0.4

#-------------------------------------------------------------------------------
# change `num_queries` from 500 in `train_multi_frame.yaml`
#-------------------------------------------------------------------------------
