##############################################################################
# Register this file in train.py as `wildtrack_only`.
##############################################################################

# starting point: `train_mot17_crowdhuman.yaml`
# dataset-type
dataset: mot_less_transforms # less preprocessing to prepare training on 3D data
# don't neet b/c dataset not of type mot_crowdhuman
#crowdhuman_train_split: train_val
train_split: train
val_split: train

mot_path_train: data/WILDTRACK
#only one sequence at a time to make comparable to distribtion metrics?
mot_path_val: data/WILDTRACK

# pre-trained detector/tracker
#resume: models/right_ref_point/checkpoint_epoch_1000.pth

epochs: 3000
lr_drop: 2

#no_vis: false
batch_size: 1

img_transform:
  max_size: 1920
  val_width: 1080

#eval_only: true
val_interval: 33
vis_and_log_interval: 99

deformable: false


lr: 0.002 # multiplied by 10
lr_backbone_names: ['backbone.0']
lr_backbone: 0.0002 # multiplied by 10
lr_linear_proj_names: ['reference_points', 'sampling_offsets']
lr_linear_proj_mult: 0.1
lr_track: 0.001 # divided by 10
overwrite_lrs: false
overwrite_lr_scheduler: false
weight_decay: 0.001 # multiplied by 10
lr_drop: 2 # from 10


multi_frame_attention: false #false
multi_frame_encoding: false #true