##############################################################################
# Register this file in train.py as `wildtrack_only`.
##############################################################################

# starting point: `train_mot17_crowdhuman.yaml`
# dataset-type
dataset: mot_less_transforms # less preprocessing to prepare training on 3D data
# don't neet b/c dataset not of type mot_crowdhuman
#crowdhuman_train_split: train_val
train_split: train
val_split: train

mot_path_train: data/WILDTRACK
#only one sequence at a time to make comparable to distribtion metrics?
mot_path_val: data/WILDTRACK

# pre-trained detector/tracker
resume: models/mot17_crowdhuman_deformable_multi_frame/checkpoint_epoch_40.pth

epochs: 500
lr_drop: 10

no_vis: false
batch_size: 1

img_transform:
  max_size: 1920
  val_width: 1080

#eval_only: true