# starting point: `train_mot17_crowdhuman.yaml`
dataset: mot_wildtrack_baseline # "mot" has to be in there for trackig"... see train.py
# also has to be registered in `trackformer/__init__.py`
# and in ``def build_dataset()` in `trackformer/datasets/__init__.py`

# need to download crowdhuman?
# probably not -- is only for detection
#crowdhuman_train_split: train_val
train_split: train
val_split: test

mot_path_train: data/WILDTRACK
#only one sequence at a time to make comparable to distribtion metrics?
mot_path_val: data/WILDTRACK

# pre-trained detector
resume: models/mot17_crowdhuman_deformable_multi_frame/checkpoint_epoch_40.pth

epochs: 40
lr_drop: 10

# `track.yaml` write_images and generate_attention_maps does not work in this file